### ISSUE TITLE
error in File "/usr/local/lib/python3.9/site-packages/garmindb/download.py", line 166, in login

### ISSUE THREAD

**Issue by thinktank9** [tcgoetz/GarminDB#143]
I have a cron job that downloads Garmin data every day but since yesterday evening its started giving an error. It's been working fine for the last couple of months and I haven't made any changes to the configuration or the environment (its runs inside a docker container so it's completely isolated). I upgraded the package with `pip install --upgrade garmindb` but I am still getting the error. See the logs below.

**To Reproduce**
Steps to reproduce the behaviour:
run `garmindb_cli.py --all --download --import --analyze --latest`

**Expected behaviour**
Should download all the updates since the last run

**Logs**
```
___Downloading Latest Data___
Traceback (most recent call last):
  File "/usr/local/bin/garmindb_cli.py", line 349, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/garmindb_cli.py", line 330, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "/usr/local/bin/garmindb_cli.py", line 111, in download_data
    if not download.login():
  File "/usr/local/lib/python3.9/site-packages/garmindb/download.py", line 166, in login
    self.display_name = self.user_prefs['displayName']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tcgoetz** [comment]
Confirmed.

**Comment by tcgoetz** [comment]
Fixed on develop branch. Are you able to test from source? Can you test the develop branch and see if it works for you?

**Comment by MarnixvBuuren** [comment]
Works! Did a download of all latest activities and monitoring-files. Thx!

**Comment by rprr** [comment]
I'm using this for the first time and am getting this error still. I have switched branch to develop. On Mac OS X.

**Comment by EmptySoft** [comment]
i try to use the develop branch to, but i cannot run the make setup command

**Comment by tcgoetz** [comment]
> I'm using this for the first time and am getting this error still. I have switched branch to develop. On Mac OS X.

After switching to the develop branch, did you build and install? `make reinstall_all`

**Comment by tcgoetz** [comment]
> Kommando nicht gefunden make: /usr/bin/bash

You don't have bash installed on your system. either install bash or change the SHELL define in defines.mk.

**Comment by thinktank9** [comment]
Works for me.

**Steps:**
1. created a docker container with all the required tools
2. inside the container, cloned the repo using `git clone -b develop --recurse-submodules git@github.com:tcgoetz/GarminDB.git`
3. inside `GarminDB` dir ran `make setup`
4. updated `/root/.GarminDb/GarminConnectConfig.json` with my settings
5. ran `make create_dbs`

it started downloading the files, see the screenshot - 

![image](https://user-images.githubusercontent.com/14940852/147249307-385b1078-3869-4393-984c-b9b17abf1836.png)

Is that what you were expecting me to check?

**Comment by thinktank9** [comment]
This is a screenshot of my script which was giving the error earlier, it's working with the fix now - 

![image](https://user-images.githubusercontent.com/14940852/147250388-48dbd517-4920-4b80-bdf7-cb437f8c6e83.png)

**Comment by EmptySoft** [comment]
> > Kommando nicht gefunden make: /usr/bin/bash
> 
> You don't have bash installed on your system. either install bash or change the SHELL define in defines.mk.
Hi Tom.!

Thanks a lot (my bash is in the linux standard path /bin/bash. But now i have a new error ...
`harald@kalymnos:~/GarminDB> make setup
cp /home/harald/GarminDB/garmindb/GarminConnectConfig.json.example /home/harald/.GarminDb/GarminConnectConfig.json
python3 -m venv --upgrade-deps /home/harald/GarminDB/.venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT]
            ENV_DIR [ENV_DIR ...]
venv: error: unrecognized arguments: --upgrade-deps
make: *** [Makefile:56: /home/harald/GarminDB/.venv] Fehler 2
harald@kalymnos:~/GarminDB>`
