### ISSUE TITLE
Errors when running make setup

### ISSUE THREAD

**Issue by olddawgpowers** [tcgoetz/GarminDB#41]
I don't get very far with make setup.  I kept getting errors on make setup so I had to clone utilities and Tcx separately.   After than when I tried to make create_db I get the following

pi@raspberrypi:~/garmin/GarminDB $ make create_db
Traceback (most recent call last):
  File "garmin.py", line 18, in <module>
    from version import print_version, python_version_check, log_version
  File "/home/pi/garmin/GarminDB/version.py", line 7, in <module>
    import utilities.version as uv
  File "/home/pi/garmin/GarminDB/utilities/__init__.py", line 11, in <module>
    from utilities.db import DbParams, DB, DBObject
  File "/home/pi/garmin/GarminDB/utilities/db.py", line 13, in <module>
    from sqlalchemy import create_engine, func, desc, extract, and_, literal_column
ModuleNotFoundError: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "garmin.py", line 18, in <module>
    from version import print_version, python_version_check, log_version
  File "/home/pi/garmin/GarminDB/version.py", line 7, in <module>
    import utilities.version as uv
  File "/home/pi/garmin/GarminDB/utilities/__init__.py", line 11, in <module>
    from utilities.db import DbParams, DB, DBObject
  File "/home/pi/garmin/GarminDB/utilities/db.py", line 13, in <module>
    from sqlalchemy import create_engine, func, desc, extract, and_, literal_column
ModuleNotFoundError: No module named 'sqlalchemy'
make: *** No rule to make target 'create_db'.  Stop.

**Comment by tcgoetz** [comment]
`make setup` should work now. I thik if you clone the subrepos separately, you will be on the wrong commit in them.

**Comment by olddawgpowers** [comment]
Unfortunately still getting errors on make setup
pi@raspberrypi:~/garmin/GarminDB $ make setup
Traceback (most recent call last):
  File "garmin.py", line 18, in <module>
    from version import print_version, python_version_check, log_version
  File "/home/pi/garmin/GarminDB/version.py", line 7, in <module>
    import utilities.version as uv
ModuleNotFoundError: No module named 'utilities.version'
Traceback (most recent call last):
  File "garmin.py", line 18, in <module>
    from version import print_version, python_version_check, log_version
  File "/home/pi/garmin/GarminDB/version.py", line 7, in <module>
    import utilities.version as uv
ModuleNotFoundError: No module named 'utilities.version'
git submodule init

**Comment by olddawgpowers** [comment]
When I tried to run make create_dbs I got the following
pi@raspberrypi:~/garmin/GarminDB $ make create_dbs
time /usr/bin/python3 garmin.py --all --download --import --analyze
make: time: Command not found
make: *** [Makefile:106: garmin] Error 127

**Comment by laurentperrinet** [comment]
Hi,

I have a similar problem at setup, encountering 

```

$ make setup
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/utilities/__init__.py", line 9, in <module>
    import version
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/version.py", line 8, in <module>
    from version_info import python_required, python_tested, version_info
ModuleNotFoundError: No module named 'version_info'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/utilities/__init__.py", line 9, in <module>
    import version
  File "/Users/laurentperrinet/quantic/Documents/outdoor/GarminDB_goetz/version.py", line 8, in <module>
    from version_info import python_required, python_tested, version_info
ModuleNotFoundError: No module named 'version_info'
```


I have tried to clone a clean version, but get the same problem...

**Comment by tcgoetz** [comment]
@laurentperrinet my bad. I didn't add a new file. Try again.

**Comment by olddawgpowers** [comment]
I get following when I tried new clone and make setup
pi@raspberrypi:~/garmin/garmin2/GarminDB $ make setup
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/garmin/garmin2/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/garmin/garmin2/GarminDB/garmin_db_config_manager.py", line 12, in <module>
    from utilities import DbParams
ImportError: cannot import name 'DbParams' from 'utilities' (unknown location)
git submodule init
Submodule 'Fit' (git@github.com:tcgoetz/Fit.git) registered for path 'Fit'
Submodule 'Tcx' (git@github.com:tcgoetz/Tcx.git) registered for path 'Tcx'
Submodule 'utilities' (git@github.com:tcgoetz/utilities.git) registered for path 'utilities'
git submodule update
Cloning into '/home/pi/garmin/garmin2/GarminDB/Fit'...
Enter passphrase for key '/home/pi/.ssh/id_rsa': Enter passphrase for key '/home/pi/.ssh/id_rsa': Enter passphrase for key '/home/pi/.ssh/id_rsa':

**Comment by olddawgpowers** [comment]
I finally got the make setup to run by cloning GarminDB to root directory.  
Now I get error when trying to make create_dbs
pi@raspberrypi:~/GarminDB $ make create_dbs
time /usr/bin/python3 garmin.py --all --download --import --analyze
make: time: Command not found
make: *** [Makefile:105: garmin] Error 127

**Comment by laurentperrinet** [comment]
my issue is solved with the addition of the missing file and everything syncs fine, many thanks!

(and sorry for getting into that issue, which I thought was related...)

**Comment by olddawgpowers** [comment]
@laurentperrinet you had no issues with create_dbs? Are you running on raspberry pi?

**Comment by laurentperrinet** [comment]
nope sorry, I am running on MacOs for which you'll get `time` as:

```
$ which time
time: shell reserved word
```

**Comment by olddawgpowers** [comment]
I am missing something.  Nothing returns when I type in which time
pi@raspberrypi:~ $ which time
pi@raspberrypi:~ $

**Comment by olddawgpowers** [comment]
@tcgoetz Thanks for the fix.  It appears to be working.  Currently Getting activities and I am at about 45% of the download.   Appreciate your work.  Was the time an issue on my side?

**Comment by tcgoetz** [comment]
> Was the time an issue on my side?

Yes and no. I developed GarminDb on MacOS and haven't tested it on Linux of any distro. Finding issues I didn't anticipate and reporting them helps make it work on all platforms.
